package com.aidou.dao.entity;

import java.util.Date;

public class SysConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.id
     *
     * @mbggenerated Wed Nov 13 21:19:39 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.id_increase
     *
     * @mbggenerated Wed Nov 13 21:19:39 CST 2019
     */
    private Long idIncrease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.type
     *
     * @mbggenerated Wed Nov 13 21:19:39 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.updated
     *
     * @mbggenerated Wed Nov 13 21:19:39 CST 2019
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.id
     *
     * @return the value of sys_config.id
     *
     * @mbggenerated Wed Nov 13 21:19:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.id
     *
     * @param id the value for sys_config.id
     *
     * @mbggenerated Wed Nov 13 21:19:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.id_increase
     *
     * @return the value of sys_config.id_increase
     *
     * @mbggenerated Wed Nov 13 21:19:39 CST 2019
     */
    public Long getIdIncrease() {
        return idIncrease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.id_increase
     *
     * @param idIncrease the value for sys_config.id_increase
     *
     * @mbggenerated Wed Nov 13 21:19:39 CST 2019
     */
    public void setIdIncrease(Long idIncrease) {
        this.idIncrease = idIncrease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.type
     *
     * @return the value of sys_config.type
     *
     * @mbggenerated Wed Nov 13 21:19:39 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.type
     *
     * @param type the value for sys_config.type
     *
     * @mbggenerated Wed Nov 13 21:19:39 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.updated
     *
     * @return the value of sys_config.updated
     *
     * @mbggenerated Wed Nov 13 21:19:39 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.updated
     *
     * @param updated the value for sys_config.updated
     *
     * @mbggenerated Wed Nov 13 21:19:39 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}