package com.aidou.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysUserLogoutExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user_logout
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user_logout
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user_logout
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_logout
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public SysUserLogoutExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_logout
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_logout
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_logout
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_logout
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_logout
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_logout
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_logout
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_logout
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_logout
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_logout
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user_logout
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andLogouStatusCodeIsNull() {
            addCriterion("logou_status_code is null");
            return (Criteria) this;
        }

        public Criteria andLogouStatusCodeIsNotNull() {
            addCriterion("logou_status_code is not null");
            return (Criteria) this;
        }

        public Criteria andLogouStatusCodeEqualTo(Integer value) {
            addCriterion("logou_status_code =", value, "logouStatusCode");
            return (Criteria) this;
        }

        public Criteria andLogouStatusCodeNotEqualTo(Integer value) {
            addCriterion("logou_status_code <>", value, "logouStatusCode");
            return (Criteria) this;
        }

        public Criteria andLogouStatusCodeGreaterThan(Integer value) {
            addCriterion("logou_status_code >", value, "logouStatusCode");
            return (Criteria) this;
        }

        public Criteria andLogouStatusCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("logou_status_code >=", value, "logouStatusCode");
            return (Criteria) this;
        }

        public Criteria andLogouStatusCodeLessThan(Integer value) {
            addCriterion("logou_status_code <", value, "logouStatusCode");
            return (Criteria) this;
        }

        public Criteria andLogouStatusCodeLessThanOrEqualTo(Integer value) {
            addCriterion("logou_status_code <=", value, "logouStatusCode");
            return (Criteria) this;
        }

        public Criteria andLogouStatusCodeIn(List<Integer> values) {
            addCriterion("logou_status_code in", values, "logouStatusCode");
            return (Criteria) this;
        }

        public Criteria andLogouStatusCodeNotIn(List<Integer> values) {
            addCriterion("logou_status_code not in", values, "logouStatusCode");
            return (Criteria) this;
        }

        public Criteria andLogouStatusCodeBetween(Integer value1, Integer value2) {
            addCriterion("logou_status_code between", value1, value2, "logouStatusCode");
            return (Criteria) this;
        }

        public Criteria andLogouStatusCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("logou_status_code not between", value1, value2, "logouStatusCode");
            return (Criteria) this;
        }

        public Criteria andLogouStatusValIsNull() {
            addCriterion("logou_status_val is null");
            return (Criteria) this;
        }

        public Criteria andLogouStatusValIsNotNull() {
            addCriterion("logou_status_val is not null");
            return (Criteria) this;
        }

        public Criteria andLogouStatusValEqualTo(String value) {
            addCriterion("logou_status_val =", value, "logouStatusVal");
            return (Criteria) this;
        }

        public Criteria andLogouStatusValNotEqualTo(String value) {
            addCriterion("logou_status_val <>", value, "logouStatusVal");
            return (Criteria) this;
        }

        public Criteria andLogouStatusValGreaterThan(String value) {
            addCriterion("logou_status_val >", value, "logouStatusVal");
            return (Criteria) this;
        }

        public Criteria andLogouStatusValGreaterThanOrEqualTo(String value) {
            addCriterion("logou_status_val >=", value, "logouStatusVal");
            return (Criteria) this;
        }

        public Criteria andLogouStatusValLessThan(String value) {
            addCriterion("logou_status_val <", value, "logouStatusVal");
            return (Criteria) this;
        }

        public Criteria andLogouStatusValLessThanOrEqualTo(String value) {
            addCriterion("logou_status_val <=", value, "logouStatusVal");
            return (Criteria) this;
        }

        public Criteria andLogouStatusValLike(String value) {
            addCriterion("logou_status_val like", value, "logouStatusVal");
            return (Criteria) this;
        }

        public Criteria andLogouStatusValNotLike(String value) {
            addCriterion("logou_status_val not like", value, "logouStatusVal");
            return (Criteria) this;
        }

        public Criteria andLogouStatusValIn(List<String> values) {
            addCriterion("logou_status_val in", values, "logouStatusVal");
            return (Criteria) this;
        }

        public Criteria andLogouStatusValNotIn(List<String> values) {
            addCriterion("logou_status_val not in", values, "logouStatusVal");
            return (Criteria) this;
        }

        public Criteria andLogouStatusValBetween(String value1, String value2) {
            addCriterion("logou_status_val between", value1, value2, "logouStatusVal");
            return (Criteria) this;
        }

        public Criteria andLogouStatusValNotBetween(String value1, String value2) {
            addCriterion("logou_status_val not between", value1, value2, "logouStatusVal");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("created is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("created is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("created =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("created <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("created >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("created >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("created <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("created <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("created in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("created not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("created between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("created not between", value1, value2, "created");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user_logout
     *
     * @mbggenerated do_not_delete_during_merge Sat Nov 09 17:49:52 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user_logout
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}