package com.aidou.dao.entity;

import java.util.Date;

public class SysUserLogout {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_logout.id
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_logout.user_id
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_logout.logou_status_code
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    private Integer logouStatusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_logout.logou_status_val
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    private String logouStatusVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_logout.created
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_logout.id
     *
     * @return the value of sys_user_logout.id
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_logout.id
     *
     * @param id the value for sys_user_logout.id
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_logout.user_id
     *
     * @return the value of sys_user_logout.user_id
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_logout.user_id
     *
     * @param userId the value for sys_user_logout.user_id
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_logout.logou_status_code
     *
     * @return the value of sys_user_logout.logou_status_code
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public Integer getLogouStatusCode() {
        return logouStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_logout.logou_status_code
     *
     * @param logouStatusCode the value for sys_user_logout.logou_status_code
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public void setLogouStatusCode(Integer logouStatusCode) {
        this.logouStatusCode = logouStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_logout.logou_status_val
     *
     * @return the value of sys_user_logout.logou_status_val
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public String getLogouStatusVal() {
        return logouStatusVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_logout.logou_status_val
     *
     * @param logouStatusVal the value for sys_user_logout.logou_status_val
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public void setLogouStatusVal(String logouStatusVal) {
        this.logouStatusVal = logouStatusVal == null ? null : logouStatusVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_logout.created
     *
     * @return the value of sys_user_logout.created
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_logout.created
     *
     * @param created the value for sys_user_logout.created
     *
     * @mbggenerated Sat Nov 09 17:49:52 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}