package com.aidou.dao.entity;

import java.util.Date;

public class TbFriendApplication {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_application.id
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_application.userid
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_application.friend_id
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    private Long friendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_application.islike
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    private Boolean islike;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_application.line_back
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    private Date lineBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_application.created
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_application.updated
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_application.status
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_application.content
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_application.mid
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    private Long mid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_application.id
     *
     * @return the value of tb_friend_application.id
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_application.id
     *
     * @param id the value for tb_friend_application.id
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_application.userid
     *
     * @return the value of tb_friend_application.userid
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_application.userid
     *
     * @param userid the value for tb_friend_application.userid
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_application.friend_id
     *
     * @return the value of tb_friend_application.friend_id
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public Long getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_application.friend_id
     *
     * @param friendId the value for tb_friend_application.friend_id
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public void setFriendId(Long friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_application.islike
     *
     * @return the value of tb_friend_application.islike
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public Boolean getIslike() {
        return islike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_application.islike
     *
     * @param islike the value for tb_friend_application.islike
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public void setIslike(Boolean islike) {
        this.islike = islike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_application.line_back
     *
     * @return the value of tb_friend_application.line_back
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public Date getLineBack() {
        return lineBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_application.line_back
     *
     * @param lineBack the value for tb_friend_application.line_back
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public void setLineBack(Date lineBack) {
        this.lineBack = lineBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_application.created
     *
     * @return the value of tb_friend_application.created
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_application.created
     *
     * @param created the value for tb_friend_application.created
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_application.updated
     *
     * @return the value of tb_friend_application.updated
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_application.updated
     *
     * @param updated the value for tb_friend_application.updated
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_application.status
     *
     * @return the value of tb_friend_application.status
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_application.status
     *
     * @param status the value for tb_friend_application.status
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_application.content
     *
     * @return the value of tb_friend_application.content
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_application.content
     *
     * @param content the value for tb_friend_application.content
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_application.mid
     *
     * @return the value of tb_friend_application.mid
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_application.mid
     *
     * @param mid the value for tb_friend_application.mid
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }
}