package com.aidou.dao.entity;

import java.util.Date;

public class TbLine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_line.id
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_line.user_id
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_line.status
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_line.created
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_line.updated
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_line.source
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_line.type
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_line.count
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_line.id
     *
     * @return the value of tb_line.id
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_line.id
     *
     * @param id the value for tb_line.id
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_line.user_id
     *
     * @return the value of tb_line.user_id
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_line.user_id
     *
     * @param userId the value for tb_line.user_id
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_line.status
     *
     * @return the value of tb_line.status
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_line.status
     *
     * @param status the value for tb_line.status
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_line.created
     *
     * @return the value of tb_line.created
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_line.created
     *
     * @param created the value for tb_line.created
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_line.updated
     *
     * @return the value of tb_line.updated
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_line.updated
     *
     * @param updated the value for tb_line.updated
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_line.source
     *
     * @return the value of tb_line.source
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_line.source
     *
     * @param source the value for tb_line.source
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_line.type
     *
     * @return the value of tb_line.type
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_line.type
     *
     * @param type the value for tb_line.type
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_line.count
     *
     * @return the value of tb_line.count
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_line.count
     *
     * @param count the value for tb_line.count
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}