    package com.aidou.dao.entity;

import java.util.Date;

public class TbNotice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.id
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.notice_type
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    private Integer noticeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.notice_type_name
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    private String noticeTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.content
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.created
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.uid
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.clear_time
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    private Date clearTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.id
     *
     * @return the value of tb_notice.id
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.id
     *
     * @param id the value for tb_notice.id
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.notice_type
     *
     * @return the value of tb_notice.notice_type
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    public Integer getNoticeType() {
        return noticeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.notice_type
     *
     * @param noticeType the value for tb_notice.notice_type
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    public void setNoticeType(Integer noticeType) {
        this.noticeType = noticeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.notice_type_name
     *
     * @return the value of tb_notice.notice_type_name
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    public String getNoticeTypeName() {
        return noticeTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.notice_type_name
     *
     * @param noticeTypeName the value for tb_notice.notice_type_name
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    public void setNoticeTypeName(String noticeTypeName) {
        this.noticeTypeName = noticeTypeName == null ? null : noticeTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.content
     *
     * @return the value of tb_notice.content
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.content
     *
     * @param content the value for tb_notice.content
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.created
     *
     * @return the value of tb_notice.created
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.created
     *
     * @param created the value for tb_notice.created
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.uid
     *
     * @return the value of tb_notice.uid
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.uid
     *
     * @param uid the value for tb_notice.uid
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.clear_time
     *
     * @return the value of tb_notice.clear_time
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    public Date getClearTime() {
        return clearTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.clear_time
     *
     * @param clearTime the value for tb_notice.clear_time
     *
     * @mbggenerated Thu Dec 26 13:56:17 CST 2019
     */
    public void setClearTime(Date clearTime) {
        this.clearTime = clearTime;
    }
}