package com.aidou.dao.entity;

import java.util.Date;

public class TbOrderError {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_error.orderId
     *
     * @mbggenerated Sat Nov 23 18:00:44 CST 2019
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_error.amout
     *
     * @mbggenerated Sat Nov 23 18:00:44 CST 2019
     */
    private Long amout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_error.created
     *
     * @mbggenerated Sat Nov 23 18:00:44 CST 2019
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_error.remark
     *
     * @mbggenerated Sat Nov 23 18:00:44 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_error.orderId
     *
     * @return the value of tb_order_error.orderId
     *
     * @mbggenerated Sat Nov 23 18:00:44 CST 2019
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_error.orderId
     *
     * @param orderid the value for tb_order_error.orderId
     *
     * @mbggenerated Sat Nov 23 18:00:44 CST 2019
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_error.amout
     *
     * @return the value of tb_order_error.amout
     *
     * @mbggenerated Sat Nov 23 18:00:44 CST 2019
     */
    public Long getAmout() {
        return amout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_error.amout
     *
     * @param amout the value for tb_order_error.amout
     *
     * @mbggenerated Sat Nov 23 18:00:44 CST 2019
     */
    public void setAmout(Long amout) {
        this.amout = amout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_error.created
     *
     * @return the value of tb_order_error.created
     *
     * @mbggenerated Sat Nov 23 18:00:44 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_error.created
     *
     * @param created the value for tb_order_error.created
     *
     * @mbggenerated Sat Nov 23 18:00:44 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_error.remark
     *
     * @return the value of tb_order_error.remark
     *
     * @mbggenerated Sat Nov 23 18:00:44 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_error.remark
     *
     * @param remark the value for tb_order_error.remark
     *
     * @mbggenerated Sat Nov 23 18:00:44 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}