package com.aidou.dao.entity;

import java.util.Date;

public class TbUserMsg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_msg.mid
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    private Long mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_msg.title
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_msg.content
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_msg.is_wechat_push
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    private Boolean isWechatPush;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_msg.created
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_msg.updated
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_msg.mid
     *
     * @return the value of tb_user_msg.mid
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_msg.mid
     *
     * @param mid the value for tb_user_msg.mid
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_msg.title
     *
     * @return the value of tb_user_msg.title
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_msg.title
     *
     * @param title the value for tb_user_msg.title
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_msg.content
     *
     * @return the value of tb_user_msg.content
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_msg.content
     *
     * @param content the value for tb_user_msg.content
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_msg.is_wechat_push
     *
     * @return the value of tb_user_msg.is_wechat_push
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public Boolean getIsWechatPush() {
        return isWechatPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_msg.is_wechat_push
     *
     * @param isWechatPush the value for tb_user_msg.is_wechat_push
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public void setIsWechatPush(Boolean isWechatPush) {
        this.isWechatPush = isWechatPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_msg.created
     *
     * @return the value of tb_user_msg.created
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_msg.created
     *
     * @param created the value for tb_user_msg.created
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_msg.updated
     *
     * @return the value of tb_user_msg.updated
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_msg.updated
     *
     * @param updated the value for tb_user_msg.updated
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}