package com.aidou.dao.entity;

import java.util.Date;

public class TbUserRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_relation.id
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_relation.s_user_id
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    private Long sUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_relation.s_uname
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    private String sUname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_relation.t_user_id
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    private Long tUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_relation.t_uname
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    private String tUname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_relation.created
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_relation.updated
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_relation.dp_status
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    private Integer dpStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_relation.remarks
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_relation.id
     *
     * @return the value of tb_user_relation.id
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_relation.id
     *
     * @param id the value for tb_user_relation.id
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_relation.s_user_id
     *
     * @return the value of tb_user_relation.s_user_id
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    public Long getsUserId() {
        return sUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_relation.s_user_id
     *
     * @param sUserId the value for tb_user_relation.s_user_id
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    public void setsUserId(Long sUserId) {
        this.sUserId = sUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_relation.s_uname
     *
     * @return the value of tb_user_relation.s_uname
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    public String getsUname() {
        return sUname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_relation.s_uname
     *
     * @param sUname the value for tb_user_relation.s_uname
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    public void setsUname(String sUname) {
        this.sUname = sUname == null ? null : sUname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_relation.t_user_id
     *
     * @return the value of tb_user_relation.t_user_id
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    public Long gettUserId() {
        return tUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_relation.t_user_id
     *
     * @param tUserId the value for tb_user_relation.t_user_id
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    public void settUserId(Long tUserId) {
        this.tUserId = tUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_relation.t_uname
     *
     * @return the value of tb_user_relation.t_uname
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    public String gettUname() {
        return tUname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_relation.t_uname
     *
     * @param tUname the value for tb_user_relation.t_uname
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    public void settUname(String tUname) {
        this.tUname = tUname == null ? null : tUname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_relation.created
     *
     * @return the value of tb_user_relation.created
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_relation.created
     *
     * @param created the value for tb_user_relation.created
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_relation.updated
     *
     * @return the value of tb_user_relation.updated
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_relation.updated
     *
     * @param updated the value for tb_user_relation.updated
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_relation.dp_status
     *
     * @return the value of tb_user_relation.dp_status
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    public Integer getDpStatus() {
        return dpStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_relation.dp_status
     *
     * @param dpStatus the value for tb_user_relation.dp_status
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    public void setDpStatus(Integer dpStatus) {
        this.dpStatus = dpStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_relation.remarks
     *
     * @return the value of tb_user_relation.remarks
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_relation.remarks
     *
     * @param remarks the value for tb_user_relation.remarks
     *
     * @mbggenerated Thu Nov 14 15:06:09 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}