package com.aidou.dao.entity;

import java.util.Date;

public class TbUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.uid
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.nikename
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private String nikename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.birthday
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.status
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.avatarurl
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private String avatarurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.wechat
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.mobile
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.sex
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.mid
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private Long mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.income
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private String income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.education
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.house_car
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private String houseCar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.marriage
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private String marriage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.household
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private String household;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.town
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private String town;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.weight
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.height
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.work
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private String work;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.school
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.last_article
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private Date lastArticle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.created
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.updated
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.real_name
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private Boolean realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.school_verification
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private Integer schoolVerification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.verification_code
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private String verificationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.last_time
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.status_name
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private String statusName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.account_status
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private Integer accountStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.account_status_name
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    private String accountStatusName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.uid
     *
     * @return the value of tb_user.uid
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.uid
     *
     * @param uid the value for tb_user.uid
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.nikename
     *
     * @return the value of tb_user.nikename
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public String getNikename() {
        return nikename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.nikename
     *
     * @param nikename the value for tb_user.nikename
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setNikename(String nikename) {
        this.nikename = nikename == null ? null : nikename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.birthday
     *
     * @return the value of tb_user.birthday
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.birthday
     *
     * @param birthday the value for tb_user.birthday
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.status
     *
     * @return the value of tb_user.status
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.status
     *
     * @param status the value for tb_user.status
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.avatarurl
     *
     * @return the value of tb_user.avatarurl
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public String getAvatarurl() {
        return avatarurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.avatarurl
     *
     * @param avatarurl the value for tb_user.avatarurl
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setAvatarurl(String avatarurl) {
        this.avatarurl = avatarurl == null ? null : avatarurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.wechat
     *
     * @return the value of tb_user.wechat
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.wechat
     *
     * @param wechat the value for tb_user.wechat
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.mobile
     *
     * @return the value of tb_user.mobile
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.mobile
     *
     * @param mobile the value for tb_user.mobile
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.sex
     *
     * @return the value of tb_user.sex
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.sex
     *
     * @param sex the value for tb_user.sex
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.mid
     *
     * @return the value of tb_user.mid
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.mid
     *
     * @param mid the value for tb_user.mid
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.income
     *
     * @return the value of tb_user.income
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public String getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.income
     *
     * @param income the value for tb_user.income
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setIncome(String income) {
        this.income = income == null ? null : income.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.education
     *
     * @return the value of tb_user.education
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.education
     *
     * @param education the value for tb_user.education
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.house_car
     *
     * @return the value of tb_user.house_car
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public String getHouseCar() {
        return houseCar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.house_car
     *
     * @param houseCar the value for tb_user.house_car
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setHouseCar(String houseCar) {
        this.houseCar = houseCar == null ? null : houseCar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.marriage
     *
     * @return the value of tb_user.marriage
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public String getMarriage() {
        return marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.marriage
     *
     * @param marriage the value for tb_user.marriage
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setMarriage(String marriage) {
        this.marriage = marriage == null ? null : marriage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.household
     *
     * @return the value of tb_user.household
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public String getHousehold() {
        return household;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.household
     *
     * @param household the value for tb_user.household
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setHousehold(String household) {
        this.household = household == null ? null : household.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.town
     *
     * @return the value of tb_user.town
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public String getTown() {
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.town
     *
     * @param town the value for tb_user.town
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setTown(String town) {
        this.town = town == null ? null : town.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.weight
     *
     * @return the value of tb_user.weight
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.weight
     *
     * @param weight the value for tb_user.weight
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.height
     *
     * @return the value of tb_user.height
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.height
     *
     * @param height the value for tb_user.height
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.work
     *
     * @return the value of tb_user.work
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public String getWork() {
        return work;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.work
     *
     * @param work the value for tb_user.work
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setWork(String work) {
        this.work = work == null ? null : work.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.school
     *
     * @return the value of tb_user.school
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.school
     *
     * @param school the value for tb_user.school
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.last_article
     *
     * @return the value of tb_user.last_article
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public Date getLastArticle() {
        return lastArticle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.last_article
     *
     * @param lastArticle the value for tb_user.last_article
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setLastArticle(Date lastArticle) {
        this.lastArticle = lastArticle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.created
     *
     * @return the value of tb_user.created
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.created
     *
     * @param created the value for tb_user.created
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.updated
     *
     * @return the value of tb_user.updated
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.updated
     *
     * @param updated the value for tb_user.updated
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.real_name
     *
     * @return the value of tb_user.real_name
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public Boolean getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.real_name
     *
     * @param realName the value for tb_user.real_name
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setRealName(Boolean realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.school_verification
     *
     * @return the value of tb_user.school_verification
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public Integer getSchoolVerification() {
        return schoolVerification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.school_verification
     *
     * @param schoolVerification the value for tb_user.school_verification
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setSchoolVerification(Integer schoolVerification) {
        this.schoolVerification = schoolVerification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.verification_code
     *
     * @return the value of tb_user.verification_code
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public String getVerificationCode() {
        return verificationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.verification_code
     *
     * @param verificationCode the value for tb_user.verification_code
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setVerificationCode(String verificationCode) {
        this.verificationCode = verificationCode == null ? null : verificationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.last_time
     *
     * @return the value of tb_user.last_time
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.last_time
     *
     * @param lastTime the value for tb_user.last_time
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.status_name
     *
     * @return the value of tb_user.status_name
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.status_name
     *
     * @param statusName the value for tb_user.status_name
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName == null ? null : statusName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.account_status
     *
     * @return the value of tb_user.account_status
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public Integer getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.account_status
     *
     * @param accountStatus the value for tb_user.account_status
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setAccountStatus(Integer accountStatus) {
        this.accountStatus = accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.account_status_name
     *
     * @return the value of tb_user.account_status_name
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public String getAccountStatusName() {
        return accountStatusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.account_status_name
     *
     * @param accountStatusName the value for tb_user.account_status_name
     *
     * @mbggenerated Wed Nov 13 14:22:30 CST 2019
     */
    public void setAccountStatusName(String accountStatusName) {
        this.accountStatusName = accountStatusName == null ? null : accountStatusName.trim();
    }
}