package com.aidou.dao.entity;

import java.util.Date;

public class TbUserMsgRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_msg_relation.id
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_msg_relation.mid
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    private Long mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_msg_relation.uid
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_msg_relation.created
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_msg_relation.updated
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_msg_relation.is_read
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    private Boolean isRead;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_msg_relation.id
     *
     * @return the value of tb_user_msg_relation.id
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_msg_relation.id
     *
     * @param id the value for tb_user_msg_relation.id
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_msg_relation.mid
     *
     * @return the value of tb_user_msg_relation.mid
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_msg_relation.mid
     *
     * @param mid the value for tb_user_msg_relation.mid
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_msg_relation.uid
     *
     * @return the value of tb_user_msg_relation.uid
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_msg_relation.uid
     *
     * @param uid the value for tb_user_msg_relation.uid
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_msg_relation.created
     *
     * @return the value of tb_user_msg_relation.created
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_msg_relation.created
     *
     * @param created the value for tb_user_msg_relation.created
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_msg_relation.updated
     *
     * @return the value of tb_user_msg_relation.updated
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_msg_relation.updated
     *
     * @param updated the value for tb_user_msg_relation.updated
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_msg_relation.is_read
     *
     * @return the value of tb_user_msg_relation.is_read
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public Boolean getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_msg_relation.is_read
     *
     * @param isRead the value for tb_user_msg_relation.is_read
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }
}