package com.aidou.dao.mapper;

import com.aidou.dao.entity.TbComment;
import com.aidou.dao.entity.TbCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Mon Oct 14 12:36:23 CST 2019
     */
    int countByExample(TbCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Mon Oct 14 12:36:23 CST 2019
     */
    int deleteByExample(TbCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Mon Oct 14 12:36:23 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Mon Oct 14 12:36:23 CST 2019
     */
    int insert(TbComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Mon Oct 14 12:36:23 CST 2019
     */
    int insertSelective(TbComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Mon Oct 14 12:36:23 CST 2019
     */
    List<TbComment> selectByExample(TbCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Mon Oct 14 12:36:23 CST 2019
     */
    TbComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Mon Oct 14 12:36:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbComment record, @Param("example") TbCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Mon Oct 14 12:36:23 CST 2019
     */
    int updateByExample(@Param("record") TbComment record, @Param("example") TbCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Mon Oct 14 12:36:23 CST 2019
     */
    int updateByPrimaryKeySelective(TbComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Mon Oct 14 12:36:23 CST 2019
     */
    int updateByPrimaryKey(TbComment record);
}