package com.aidou.dao.mapper;

import com.aidou.dao.entity.TbFriendApplication;
import com.aidou.dao.entity.TbFriendApplicationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbFriendApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_application
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    int countByExample(TbFriendApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_application
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    int deleteByExample(TbFriendApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_application
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_application
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    int insert(TbFriendApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_application
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    int insertSelective(TbFriendApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_application
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    List<TbFriendApplication> selectByExample(TbFriendApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_application
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    TbFriendApplication selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_application
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbFriendApplication record, @Param("example") TbFriendApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_application
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    int updateByExample(@Param("record") TbFriendApplication record, @Param("example") TbFriendApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_application
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    int updateByPrimaryKeySelective(TbFriendApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_application
     *
     * @mbggenerated Tue Jul 09 10:44:15 CST 2019
     */
    int updateByPrimaryKey(TbFriendApplication record);
}