package com.aidou.dao.mapper;

import com.aidou.dao.entity.TbLineRecord;
import com.aidou.dao.entity.TbLineRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbLineRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line_record
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    int countByExample(TbLineRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line_record
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    int deleteByExample(TbLineRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line_record
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line_record
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    int insert(TbLineRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line_record
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    int insertSelective(TbLineRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line_record
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    List<TbLineRecord> selectByExample(TbLineRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line_record
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    TbLineRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line_record
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbLineRecord record, @Param("example") TbLineRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line_record
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    int updateByExample(@Param("record") TbLineRecord record, @Param("example") TbLineRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line_record
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    int updateByPrimaryKeySelective(TbLineRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line_record
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    int updateByPrimaryKey(TbLineRecord record);
}