package com.aidou.dao.mapper;

import com.aidou.dao.entity.TbLine;
import com.aidou.dao.entity.TbLineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    int countByExample(TbLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    int deleteByExample(TbLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    int insert(TbLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    int insertSelective(TbLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    List<TbLine> selectByExample(TbLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    TbLine selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbLine record, @Param("example") TbLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    int updateByExample(@Param("record") TbLine record, @Param("example") TbLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    int updateByPrimaryKeySelective(TbLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line
     *
     * @mbggenerated Tue Jul 02 16:42:19 CST 2019
     */
    int updateByPrimaryKey(TbLine record);
}