package com.aidou.dao.mapper;

import com.aidou.dao.entity.TbNotice;
import com.aidou.dao.entity.TbNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated Thu Dec 26 13:22:33 CST 2019
     */
    int countByExample(TbNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated Thu Dec 26 13:22:33 CST 2019
     */
    int deleteByExample(TbNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated Thu Dec 26 13:22:33 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated Thu Dec 26 13:22:33 CST 2019
     */
    int insert(TbNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated Thu Dec 26 13:22:33 CST 2019
     */
    int insertSelective(TbNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated Thu Dec 26 13:22:33 CST 2019
     */
    List<TbNotice> selectByExample(TbNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated Thu Dec 26 13:22:33 CST 2019
     */
    TbNotice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated Thu Dec 26 13:22:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbNotice record, @Param("example") TbNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated Thu Dec 26 13:22:33 CST 2019
     */
    int updateByExample(@Param("record") TbNotice record, @Param("example") TbNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated Thu Dec 26 13:22:33 CST 2019
     */
    int updateByPrimaryKeySelective(TbNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated Thu Dec 26 13:22:33 CST 2019
     */
    int updateByPrimaryKey(TbNotice record);
}