package com.aidou.dao.mapper;

import com.aidou.dao.entity.TbTopicSelectUserRelation;
import com.aidou.dao.entity.TbTopicSelectUserRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTopicSelectUserRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select_user_relation
     *
     * @mbggenerated Thu Dec 26 18:21:47 CST 2019
     */
    int countByExample(TbTopicSelectUserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select_user_relation
     *
     * @mbggenerated Thu Dec 26 18:21:47 CST 2019
     */
    int deleteByExample(TbTopicSelectUserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select_user_relation
     *
     * @mbggenerated Thu Dec 26 18:21:47 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select_user_relation
     *
     * @mbggenerated Thu Dec 26 18:21:47 CST 2019
     */
    int insert(TbTopicSelectUserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select_user_relation
     *
     * @mbggenerated Thu Dec 26 18:21:47 CST 2019
     */
    int insertSelective(TbTopicSelectUserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select_user_relation
     *
     * @mbggenerated Thu Dec 26 18:21:47 CST 2019
     */
    List<TbTopicSelectUserRelation> selectByExample(TbTopicSelectUserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select_user_relation
     *
     * @mbggenerated Thu Dec 26 18:21:47 CST 2019
     */
    TbTopicSelectUserRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select_user_relation
     *
     * @mbggenerated Thu Dec 26 18:21:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbTopicSelectUserRelation record, @Param("example") TbTopicSelectUserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select_user_relation
     *
     * @mbggenerated Thu Dec 26 18:21:47 CST 2019
     */
    int updateByExample(@Param("record") TbTopicSelectUserRelation record, @Param("example") TbTopicSelectUserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select_user_relation
     *
     * @mbggenerated Thu Dec 26 18:21:47 CST 2019
     */
    int updateByPrimaryKeySelective(TbTopicSelectUserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select_user_relation
     *
     * @mbggenerated Thu Dec 26 18:21:47 CST 2019
     */
    int updateByPrimaryKey(TbTopicSelectUserRelation record);
}