package com.aidou.dao.mapper;

import com.aidou.dao.entity.TbTopicSelect;
import com.aidou.dao.entity.TbTopicSelectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTopicSelectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    int countByExample(TbTopicSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    int deleteByExample(TbTopicSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    int insert(TbTopicSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    int insertSelective(TbTopicSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    List<TbTopicSelect> selectByExampleWithBLOBs(TbTopicSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    List<TbTopicSelect> selectByExample(TbTopicSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbTopicSelect record, @Param("example") TbTopicSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") TbTopicSelect record, @Param("example") TbTopicSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic_select
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    int updateByExample(@Param("record") TbTopicSelect record, @Param("example") TbTopicSelectExample example);
}