package com.aidou.dao.mapper;

import com.aidou.dao.entity.TbTopic;
import com.aidou.dao.entity.TbTopicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    int countByExample(TbTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    int deleteByExample(TbTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    int insert(TbTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    int insertSelective(TbTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    List<TbTopic> selectByExampleWithBLOBs(TbTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    List<TbTopic> selectByExample(TbTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    TbTopic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbTopic record, @Param("example") TbTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") TbTopic record, @Param("example") TbTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    int updateByExample(@Param("record") TbTopic record, @Param("example") TbTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    int updateByPrimaryKeySelective(TbTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(TbTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbggenerated Thu Dec 26 09:50:45 CST 2019
     */
    int updateByPrimaryKey(TbTopic record);
}