package com.aidou.dao.mapper;

import com.aidou.dao.entity.TbUserImg;
import com.aidou.dao.entity.TbUserImgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbUserImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_img
     *
     * @mbggenerated Thu Nov 21 22:42:12 CST 2019
     */
    int countByExample(TbUserImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_img
     *
     * @mbggenerated Thu Nov 21 22:42:12 CST 2019
     */
    int deleteByExample(TbUserImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_img
     *
     * @mbggenerated Thu Nov 21 22:42:12 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_img
     *
     * @mbggenerated Thu Nov 21 22:42:12 CST 2019
     */
    int insert(TbUserImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_img
     *
     * @mbggenerated Thu Nov 21 22:42:12 CST 2019
     */
    int insertSelective(TbUserImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_img
     *
     * @mbggenerated Thu Nov 21 22:42:12 CST 2019
     */
    List<TbUserImg> selectByExampleWithBLOBs(TbUserImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_img
     *
     * @mbggenerated Thu Nov 21 22:42:12 CST 2019
     */
    List<TbUserImg> selectByExample(TbUserImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_img
     *
     * @mbggenerated Thu Nov 21 22:42:12 CST 2019
     */
    TbUserImg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_img
     *
     * @mbggenerated Thu Nov 21 22:42:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbUserImg record, @Param("example") TbUserImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_img
     *
     * @mbggenerated Thu Nov 21 22:42:12 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") TbUserImg record, @Param("example") TbUserImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_img
     *
     * @mbggenerated Thu Nov 21 22:42:12 CST 2019
     */
    int updateByExample(@Param("record") TbUserImg record, @Param("example") TbUserImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_img
     *
     * @mbggenerated Thu Nov 21 22:42:12 CST 2019
     */
    int updateByPrimaryKeySelective(TbUserImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_img
     *
     * @mbggenerated Thu Nov 21 22:42:12 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(TbUserImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_img
     *
     * @mbggenerated Thu Nov 21 22:42:12 CST 2019
     */
    int updateByPrimaryKey(TbUserImg record);
}