package com.aidou.dao.mapper;

import com.aidou.dao.entity.TbUserMsg;
import com.aidou.dao.entity.TbUserMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbUserMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_msg
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    int countByExample(TbUserMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_msg
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    int deleteByExample(TbUserMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_msg
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    int deleteByPrimaryKey(Long mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_msg
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    int insert(TbUserMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_msg
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    int insertSelective(TbUserMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_msg
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    List<TbUserMsg> selectByExample(TbUserMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_msg
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    TbUserMsg selectByPrimaryKey(Long mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_msg
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbUserMsg record, @Param("example") TbUserMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_msg
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    int updateByExample(@Param("record") TbUserMsg record, @Param("example") TbUserMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_msg
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    int updateByPrimaryKeySelective(TbUserMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_msg
     *
     * @mbggenerated Thu Jul 25 10:22:26 CST 2019
     */
    int updateByPrimaryKey(TbUserMsg record);
}