server:
  port: 8991
  servlet:
    context-path: /rm
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 8192






spring:
  servlet:
   multipart:
     max-file-size: 2MB
  application:
    name: aidou-web
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true



  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://116.62.60.155:3306/aidou?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 010203Aa!
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 50
      test-on-borrow: true
      max-wait:  60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-return: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  redis:
  # Redis数据库索引（默认为0）
    database: 0
    host: 116.62.60.155
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 010203a
    jedis:
      pool:
      # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1s
        # 连接池中的最小空闲连接
        min-idle: 0
    timeout: 5000s






mybatis:
  type-aliases-package: com.aidou.dao.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  not-empty: true
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#图片保存地址
IMAGE_SERVER_URL: http://cdn.udtp.cn/




logging:

  level:
    com.aidou.dao.mapper: info




















